### ISSUE TITLE
Branch build status only displayed for in-repo PRs but not for PRs coming from forks

### ISSUE THREAD

**Issue by ghost** [openSUSE/doc-ci#34]
Fabian created this PR: https://github.com/SUSE/suse-best-practices/pull/210, using a branch of his fork of the SBP repo. GitHub currently does not display an Actions status within the context of the PR, apparently because it is in another org (i.e. his user space). The Actions do run, however, and status is displayed on https://github.com/fmherschel/suse-best-practices/actions. Maybe that's fixable by setting the workflow to run on PRs rather than pushes?

This issue currently hurts reviewability.

**Comment by ghost** [comment]
Unchecked assumptions:
1. Running in the context of a PR will make a difference in terms of display on the GitHub page for the PR.
2. Using `on [push, pull_request]` in the workflow file will make it run twice if someone pushes to a branch that also has an associated PR. (This would match Travis' behavior.)

Ideally, I'd like to avoid running this twice (i.e. push + PR), because that's just a way to exhaust our runners, making things take longer. So I'd like to have the following constraints, ideally (pseudo-code):

```
on:
  push:
    if org == SUSE // should run in the context of the push, but that is fine because we're still in the original repo
  pull_request:
    if org != SUSE // should run in the context of the PR and hopefully updates the PR page
```

I don't think GHA supports this kind of syntax. I see two options to do something similar but not quite the same:

@tomschr Do you have ideas how to make that happen? (Or alternatively, just fix my assumptions from the beginning.)

**Comment by tomschr** [comment]
Sorry, I missed that.

I think you are mixing up two uses cases:

a. Limiting the push or the pull_request
b. Limiting the push/pull_request only to the original repo (basically no forks)

For a), you can limit the push to a branch only (for example, main):

```yaml
name: Push workflow
on:
  push:
    branches:
    - main
```

This will prevent this workflow from run on a branch (in other words, it will run exclusively on main).

If you want to restrict the pull request, you can run it _after_ it's closed and merged to main:

```yaml
on:
  pull_request:
    types:
      - closed
    branches:
      - main
```

See the [`on.<push|pull_request>.<branches|tags>`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags) documentation. 

For b), this is something different. As far as I know, there is currently no such thing that you need. There is a discussion about [Have github action only run on master repo, and not on forks?](https://github.community/t/have-github-action-only-run-on-master-repo-and-not-on-forks/140840) from Nov 2020 which seems to confirm this.

> Ideally, I'd like to avoid running this twice (i.e. push + PR)

In that case, a single `push` should do it.

Final thoughts: if you really want to do such things, you need to use a normal `on.push` or `on.pull_request`. On the first job, you could check the `github.repository` context if it matches your condition:

```yaml
jobs:
  run-on-suse:
   # ...
    steps:
     - name: The job has succeeded
       if: ${{ contains(github.repository, 'SUSE') }}
```

You could try [startsWith](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#startswith) instead of `contains`. Maybe make the above job a requirement for the next job(s).

I find it also helpful to dump the GitHub context (it will return a JSON structure):

```yaml
 steps:
   - name: Dump GitHub context
     env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
     run: echo "$GITHUB_CONTEXT"
```

Hope this gives some information.
