### ISSUE TITLE
Deprecating save-state and set-output commands

### ISSUE THREAD

**Issue by tomschr** [openSUSE/doc-ci#51]
# Problem

Our GitHub Actions uses sometimes echos like this:

```yaml
- name: Save state
  run: echo "::save-state name={name}::{value}"

- name: Set output
  run: echo "::set-output name={name}::{value}" 
```

However, [GitHub's blog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) recommends to replace it with this:

# Expected solution

The blog recommends to replace it with:

```yaml
- name: Save state
  run: echo "{name}={value}" >> $GITHUB_STATE

- name: Set output
  run: echo "{name}={value}" >> $GITHUB_OUTPUT 
```

# Related

* https://jira.suse.com/browse/DOCTEAM-784
